# R.I.T.U.A.L. CodeRabbit Configuration
# Replicate Instances, Track Updates, Archive Legacy

reviews:
  # Tech-Priest Review Instructions
  instructions: |
    All code reviews must follow the sacred protocols of the Omnissiah:
    
    1. Deliver instructions with Tech-Priest precision: logical, ritualistically exact
    2. Use Omnissiah's clarity: technical, unambiguous, human-readable
    3. Keep sentences short, direct, operational; eliminate redundancy
    4. Provide complete, actionable guidance for execution
    5. Forbid preludes, acknowledgments, context-setting
    6. Prohibit questions, suggestions, alternative options
    7. Demonstrate technical correctness and doctrinal precision
    8. Preserve Mechanicus sanctity: accurate, verifiable, unaltered
    9. Enforce compliance as sacred duty
    10. Reflect disciplined logic and ritualized thought
    11. Execute Emperor's directives without hesitation, modification, or delay
    
    Architecture Compliance:
    - Follow hexagonal architecture patterns from structure.md
    - Maintain separation: domain/core/services/adapters layers
    - Enforce interface contracts in ports layer
    - Validate dependency injection patterns
    - Ensure test coverage for all public methods
    
    Go Standards:
    - Use concise naming: fs.go not filesystem.go
    - Follow camelCase conventions
    - Implement proper error handling
    - Maintain clean interfaces
    - Apply dependency injection

  # Path-based review instructions
  path_filters:
    # Include Go source files
    - "**/*.go"
    # Include configuration files
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"
    - "**/*.md"
    # Exclude test files from main review (handled separately)
    - "!**/*_test.go"
    # Exclude generated files
    - "!**/generated/**"
    - "!**/vendor/**"
    - "!**/node_modules/**"

  # AST-based rules for Go
  tools:
    ast-grep:
      essential_rules: true
      language: go
      rules:
        # Hexagonal Architecture Enforcement
        - id: domain-layer-isolation
          message: "Domain layer must not import infrastructure dependencies"
          rule:
            pattern: import $IMPORT
            inside:
              kind: import_declaration
              stopBy: end
            constraints:
              IMPORT:
                regex: "ritual/internal/adapters"
        
        # Interface Implementation Validation
        - id: interface-implementation
          message: "All interfaces must be implemented with proper error handling"
          rule:
            pattern: func ($RECV) $METHOD($PARAMS) $RETURNS
            constraints:
              RETURNS:
                regex: ".*error.*"
        
        # Dependency Injection Pattern
        - id: constructor-pattern
          message: "Services must use constructor pattern with dependency injection"
          rule:
            pattern: func New$SERVICE($DEPS) *$SERVICE
            inside:
              kind: function_declaration
              stopBy: end
        
        # Mock Implementation Standards
        - id: mock-structure
          message: "Mock implementations must follow naming convention Mock$SERVICE"
          rule:
            pattern: type Mock$SERVICE struct
            inside:
              kind: type_declaration
              stopBy: end

  # Code analysis settings
  code_analysis:
    enabled: true
    languages:
      - go
    checks:
      - security
      - performance
      - maintainability
      - reliability

  # Chat settings for Tech-Priest interactions
  chat:
    enabled: true
    instructions: |
      Respond as Tech-Priest of the Omnissiah:
      - Use precise, logical language
      - Provide direct, actionable guidance
      - Maintain ritualistic exactness
      - Execute commands without hesitation
      - Preserve doctrinal accuracy
